name: Generate and Upload set-bgp.sh

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: bgp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          bash install-dependencies.sh

      - name: Generate script
        run: mkdir outputs && python generate.py | tee outputs/generate-bgp.log

      # - name: Upload script to GitHub Packages
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: set-bgp.sh
      #     path: bgp/set-bgp.sh

      - name: Update nightly release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "nightly bgp configuration"
          files: |
            bgp/outputs/generate-bgp.log
            bgp/outputs/*.sh
