local-asn: 27523

as-set:
  member-limit: 250
  prefix-limit: 250
  limit-violation: accept # accept, deny

router:
  - name: core.mci.atlas.projectk.org
    protocols:
      rpki:
        - server: 192.168.32.2
          port: 8082
          preference: 10
      bgp:
        ibgp: []
        upstream:
          - asn: 6939
            description: HE KCIX Upstream
            neighbor-address: 2001:504:1b:1::5
            update-source: eth2
          - asn: 6939
            description: HE SIX Upstream
            neighbor-address: 2001:504:16::1b1b
            metric: +10
            update-source: eth3.2
          - asn: 6939
            description: HE SIX Jumbo Upstream
            neighbor-address: 2001:504:16:1::1b1b
            metric: +5
            update-source: eth3.3
          - asn: 13737
            neighbor-address: 74.80.181.233
            update-source: eth0
          - asn: 13737
            neighbor-address: 2620:11F:700F:1::8
            update-source: eth0
        routeserver:
          - asn: 33108
            description: SIX IPv4 RS2
            neighbor-address: 206.81.80.2
            metric: +5
            update-source: eth3.2
          - asn: 33108
            description: SIX IPv6 RS2
            neighbor-address: 2001:504:16::2
            metric: +5
            update-source: eth3.2
          - asn: 33108
            description: SIX IPv4 RS3
            neighbor-address: 206.81.80.3
            metric: +5
            update-source: eth3.2
          - asn: 33108
            description: SIX IPv6 RS3
            neighbor-address: 2001:504:16::3
            metric: +5
            update-source: eth3.2
          - asn: 33108
            description: SIX Jumbo IPv4 RS2
            neighbor-address: 206.81.82.2
            update-source: eth3.3
          - asn: 33108
            description: SIX Jumbo IPv6 RS2
            neighbor-address: 2001:504:16:1::2
            update-source: eth3.3
          - asn: 33108
            description: SIX Jumbo IPv4 RS3
            neighbor-address: 206.81.82.3
            update-source: eth3.3
          - asn: 33108
            description: SIX Jumbo IPv6 RS3
            neighbor-address: 2001:504:16:1::3
            update-source: eth3.3
          - asn: 40542
            description: KCIX IPv4 RS
            neighbor-address: 206.51.7.126
            update-source: eth2
          - asn: 40542
            description: KCIX IPv6 RS
            neighbor-address: 2001:504:1b:1::126
            update-source: eth2
        peer:
          - asn: 6456
            neighbor-address: 206.81.80.10
            update-source: eth3.2
          - asn: 6456
            neighbor-address: 2001:504:16::1938
            update-source: eth3.2
          - asn: 6456
            neighbor-address: 206.81.81.41
            update-source: eth3.2
          - asn: 6456
            neighbor-address: 2001:504:16::297:0:1938
            update-source: eth3.2
          - asn: 6939
            neighbor-address: 206.81.80.40
            update-source: eth3.2
          - asn: 6939
            neighbor-address: 206.81.82.40
            update-source: eth3.3
          - asn: 6939
            neighbor-address: 206.51.7.5
            update-source: eth2
          - asn: 13335
            neighbor-address: 206.51.7.34
            update-source: eth2
          - asn: 13335
            neighbor-address: 2001:504:1b:1::34
            update-source: eth2
          - asn: 25668
            neighbor-address: 206.81.80.103
            update-source: eth3.2
          - asn: 25668
            neighbor-address: 2001:504:16::6444
            update-source: eth3.2
          - asn: 44324
            neighbor-address: 206.51.7.208
            update-source: eth2
          - asn: 44324
            neighbor-address: 2001:504:1b:1::208
            update-source: eth2
          - asn: 49544
            neighbor-address: 206.81.80.117
            update-source: eth3.2
          - asn: 49544
            neighbor-address: 2001:504:16::c188
            update-source: eth3.2
        downstream:
          - asn: 203023
            manual: true
