local-asn: 27523

as-set:
  member-limit: 250
  prefix-limit: 250
  limit-violation: accept # accept, deny

router:
  - name: core.mci.atlas.projectk.org
    src:
      ipv4: 23.175.184.1
      ipv6: 2602:f93b:131::1
    custom-config: |
      delete policy prefix-list6 CERNET-0
      set policy prefix-list6 CERNET-0 rule 10 action permit
      set policy prefix-list6 CERNET-0 rule 10 prefix 240c:c000::/20
      set policy prefix-list6 CERNET-0 rule 10 le 128
      delete policy prefix-list6 Tunnel-Endpoints
      set policy prefix-list6 Tunnel-Endpoints rule 10 action permit
      set policy prefix-list6 Tunnel-Endpoints rule 10 prefix 2403:ad80:88:44fd::9c38/128
      set policy prefix-list6 Tunnel-Endpoints rule 10 le 128
      delete policy as-path-list AS7018
      set policy as-path-list AS7018 rule 10 action permit
      set policy as-path-list AS7018 rule 10 regex _7018_
    protocols:
      rpki:
        - server: 192.168.32.2
          port: 8082
          preference: 10
      bgp:
        ibgp:
          - description: BGP Tunnel to SEA
            neighbor-address: 169.254.20.2
            simple-out: true
            local-pref: 180
            update-source: tun10
          - description: BGP Tunnel to TYO
            neighbor-address: 169.254.20.5
            simple-out: true
            local-pref: 180
            update-source: tun20
          - description: BGP Tunnel to TYO
            neighbor-address: 2602:f93b:ffff:ffff:5:1:0:1
            simple-out: true
            local-pref: 180
            post-import-accept:
              - action: deny
                match: ipv6 address prefix-list Tunnel-Endpoints
            update-source: tun20
        upstream:
          - asn: 945
            neighbor-address: 206.51.7.160
            update-source: eth2
            post-import-accept:
              - action: deny
                match: as-path AS7018
          - asn: 945
            neighbor-address: 2001:504:1b:1::160
            local-pref: 99
            update-source: eth2
          - asn: 6939
            # example
            # prepend: "27523 27523 27523"
            # post-import-accept:
            #   - action: permit
            #     match: ipv6 address prefix-list CERNET-0
            #     set: "local-preference '500'"
            description: HE KCIX Upstream
            neighbor-address: 2001:504:1b:1::5
            update-source: eth2
          - asn: 6939
            description: HE SIX Upstream
            neighbor-address: 2001:504:16::1b1b
            metric: "+10"
            update-source: eth3.2
          - asn: 6939
            description: HE SIX Jumbo Upstream
            neighbor-address: 2001:504:16:1::1b1b
            metric: "+5"
            update-source: eth3.3
          - asn: 13737
            neighbor-address: 74.80.181.233
            update-source: eth0
          - asn: 13737
            neighbor-address: 2620:11f:700f:1::8
            update-source: eth0
        routeserver:
          - asn: 33108
            description: SIX IPv4 RS2
            neighbor-address: 206.81.80.2
            metric: "+5"
            update-source: eth3.2
          - asn: 33108
            description: SIX IPv6 RS2
            neighbor-address: 2001:504:16::2
            metric: "+5"
            update-source: eth3.2
          - asn: 33108
            description: SIX IPv4 RS3
            neighbor-address: 206.81.80.3
            metric: "+5"
            update-source: eth3.2
          - asn: 33108
            description: SIX IPv6 RS3
            neighbor-address: 2001:504:16::3
            metric: "+5"
            update-source: eth3.2
          - asn: 33108
            description: SIX Jumbo IPv4 RS2
            neighbor-address: 206.81.82.2
            update-source: eth3.3
          - asn: 33108
            description: SIX Jumbo IPv6 RS2
            neighbor-address: 2001:504:16:1::2
            update-source: eth3.3
          - asn: 33108
            description: SIX Jumbo IPv4 RS3
            neighbor-address: 206.81.82.3
            update-source: eth3.3
          - asn: 33108
            description: SIX Jumbo IPv6 RS3
            neighbor-address: 2001:504:16:1::3
            update-source: eth3.3
          - asn: 40542
            description: KCIX IPv4 RS
            neighbor-address: 206.51.7.126
            update-source: eth2
          - asn: 40542
            description: KCIX IPv6 RS
            neighbor-address: 2001:504:1b:1::126
            update-source: eth2
          - asn: 210979
            description: Pigeon IX MCI RS
            neighbor-address: 2602:f9f6:7e0:5::1
            local-pref: 125
            update-source: br5
        peer:
          - asn: 1828
            description: Unitas Global KCIX
            neighbor-address: 206.51.7.54
            update-source: eth2
          - asn: 1828
            description: Unitas Global KCIX
            neighbor-address: 2001:504:1b:1::54
            update-source: eth2
          - asn: 1828
            description: Unitas Global SIX
            neighbor-address: 206.81.80.36
            metric: "+5"
            update-source: eth3.2
          - asn: 1828
            description: Unitas Global SIX
            neighbor-address: 2001:504:16::724
            metric: "+5"
            update-source: eth3.2
          - asn: 6456
            neighbor-address: 206.81.80.10
            update-source: eth3.2
          - asn: 6456
            neighbor-address: 2001:504:16::1938
            update-source: eth3.2
          - asn: 6456
            neighbor-address: 206.81.81.41
            update-source: eth3.2
          - asn: 6456
            neighbor-address: 2001:504:16::297:0:1938
            update-source: eth3.2
          - asn: 6939
            neighbor-address: 206.81.80.40
            update-source: eth3.2
          - asn: 6939
            neighbor-address: 206.81.82.40
            update-source: eth3.3
          - asn: 6939
            neighbor-address: 206.51.7.5
            update-source: eth2
          - asn: 13335
            neighbor-address: 206.51.7.34
            update-source: eth2
          - asn: 13335
            neighbor-address: 2001:504:1b:1::34
            update-source: eth2
          - asn: 13335
            description: Cloudflare SIX
            neighbor-address: 206.81.81.10
            metric: "+5"
            update-source: eth3.2
          - asn: 13335
            description: Cloudflare SIX
            neighbor-address: 2001:504:16::3417
            metric: "+5"
            update-source: eth3.2
          - asn: 13335
            description: Cloudflare SIX
            neighbor-address: 206.81.81.58
            metric: "+5"
            update-source: eth3.2
          - asn: 13335
            description: Cloudflare SIX
            neighbor-address: 2001:504:16::314:0:3417
            metric: "+5"
            update-source: eth3.2
          - asn: 15169
            description: Google SIX
            neighbor-address: 206.81.80.17
            metric: "+5"
            password: jutran7dEbUwr6c9
            update-source: eth3.2
          - asn: 15169
            description: Google SIX
            neighbor-address: 2001:504:16::3b41
            metric: "+5"
            password: jutran7dEbUwr6c9
            update-source: eth3.2
          - asn: 15169
            description: Google SIX
            neighbor-address: 206.81.80.69
            password: jutran7dEbUwr6c9
            update-source: eth3.2
          - asn: 15169
            description: Google SIX
            neighbor-address: 2001:504:16::69:0:3b41
            password: jutran7dEbUwr6c9
            update-source: eth3.2
          - asn: 25668
            neighbor-address: 206.81.80.103
            update-source: eth3.2
          - asn: 25668
            neighbor-address: 2001:504:16::6444
            update-source: eth3.2
          - asn: 44324
            neighbor-address: 206.51.7.208
            update-source: eth2
          - asn: 44324
            neighbor-address: 2001:504:1b:1::208
            update-source: eth2
          - asn: 49544
            neighbor-address: 206.81.80.117
            update-source: eth3.2
          - asn: 49544
            neighbor-address: 2001:504:16::c188
            update-source: eth3.2
        downstream:
          - asn: 142551
            neighbor-address: 2602:f93b:ffff:131::14:2551:1
            update-source: eth6
          - asn: 199310
            neighbor-address: 2602:f93b:ffff:131::19:9310:1
            update-source: eth6
          - asn: 203023
            neighbor-address: 2602:f93b:ffff:131::20:3023:1
            update-source: eth6
          - asn: 215575
            neighbor-address: 2602:f93b:ffff:131::21:5575:1
            update-source: eth6
          - asn: 401009
            neighbor-address: 2602:f93b:ffff:131::40:1009:1
            update-source: eth6

  - name: core.sea.atlas.projectk.org
    protocols:
      rpki:
        - server: rtr.rpki.cloudflare.com
          port: 8282
          preference: 10
      bgp:
        ibgp:
          - description: BGP Tunnel to MCI
            neighbor-address: 169.254.20.1
            update-source: tun10
        upstream:
          - asn: 50131
            manual: true
        routeserver: []
        peer: []
        downstream: []

  - name: core.tyo.atlas.projectk.org
    src:
      ipv4: 103.27.185.43
      ipv6: 2602:f93b:151::1
    custom-config: |
      delete policy prefix-list6 Tunnel-Endpoints
      set policy prefix-list6 Tunnel-Endpoints rule 10 action permit
      set policy prefix-list6 Tunnel-Endpoints rule 10 prefix 2602:f93b:131::1/128
      set policy prefix-list6 Tunnel-Endpoints rule 10 le 128
    protocols:
      rpki:
        - server: rtr.rpki.cloudflare.com
          port: 8282
          preference: 10
      bgp:
        ibgp:
          - description: BGP Tunnel to MCI
            neighbor-address: 169.254.20.6
            update-source: tun20
            post-export-accept:
              - action: deny
                match: as-path AS-Except-China
          - description: BGP Tunnel to MCI
            neighbor-address: 2602:f93b:ffff:ffff:3:1:0:1
            update-source: tun20
            simple-out: true
            post-import-accept:
              - action: deny
                match: ipv6 address prefix-list Tunnel-Endpoints
        upstream:
          - asn: 134835
            neighbor-address: 10.1.52.253
            update-source: 103.27.185.43
            multihop: 2
            post-import-accept:
              - action: deny
                match: as-path AS-Except-China
          - asn: 134835
            neighbor-address: 2403:ad80:8f:ffff::253
            update-source: 2403:ad80:88:44fd::9c38
            multihop: 2
            post-import-accept:
              - action: deny
                match: as-path AS-Except-China
        routeserver: []
        peer: []
        downstream: []
